Repository RevenueCat/purchases-capacitor, pull requests merged in 2023-11, with the labels that each got.

#146 Release/7.1.0
  .gitignore
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  VERSIONS.md
  android/src/main/java/com/revenuecat/purchases/capacitor/PurchasesPlugin.kt
  ios/Plugin/PurchasesPlugin.swift
  package.json
Labels: next_release

#153 `CI`: disable `prepare-next-version`
  .circleci/config.yml
  fastlane/Fastfile
Labels: ci

#157 Trusted entitlements: Add trusted entitlements support
  README.md
  android/src/main/java/com/revenuecat/purchases/capacitor/PurchasesPlugin.kt
  example/purchase-tester/src/components/FunctionTesterContainer.tsx
  fastlane/README.md
  ios/Plugin/PurchasesPlugin.swift
Labels: feat
