Repository RevenueCat/purchases-capacitor, pull requests merged in 2024-03, with the labels that each got.

#217 Fix iOS PHC version when running tests
  fastlane/Fastfile
  ios/Podfile
Labels: test

#219 Add 6.1.2 to changelog
  CHANGELOG.md
  VERSIONS.md
Labels: documentation

#222 Adds`Purchases.getCurrentOfferingForPlacement(placementID)` and `Purchases.syncAttributesAndOfferingsIfNeeded()`
  README.md
  android/src/main/java/com/revenuecat/purchases/capacitor/PurchasesPlugin.kt
  example/purchase-tester/src/components/FunctionTesterContainer.tsx
  ios/Plugin/PurchasesPlugin.m
  ios/Plugin/PurchasesPlugin.swift
  src/definitions.ts
  src/web.ts
Labels: feat

#225 Fix `getCurrentOfferingForPlacement` API issue
  .circleci/config.yml
  README.md
  example/purchase-tester/src/components/FunctionTesterContainer.tsx
  src/definitions.ts
  src/web.ts
Labels: refactor

#220 Create RELEASING.md
  RELEASING.md
Labels: documentation

#229 Update CircleCI android machine tag
  .circleci/config.yml
Labels: ci
