Repository RevenueCat/purchases-capacitor, pull requests merged in 2024-08, with the labels that each got.

#297 Release/8.0.0
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  VERSIONS.md
  android/src/main/java/com/revenuecat/purchases/capacitor/PurchasesPlugin.kt
  ios/Plugin/PurchasesPlugin.swift
  package.json
Labels: next_release

#294 Add support new native majors
  README.md
  RevenueCatPurchasesCapacitor.podspec
  android/build.gradle
  android/src/main/java/com/revenuecat/purchases/capacitor/PurchasesPlugin.kt
  example/purchase-tester/src/components/FunctionTesterContainer.tsx
  ios/Plugin/PurchasesPlugin.m
  ios/Plugin/PurchasesPlugin.swift
  ios/Podfile
  package.json
  src/definitions.ts
  src/web.ts
Labels: dependencies, breaking

#307 [EXTERNAL] Make syncPurchases function to actually returning a promise (#305) by @jarvisluong
  android/src/main/java/com/revenuecat/purchases/capacitor/PurchasesPlugin.kt
  ios/Plugin/PurchasesPlugin.m
Labels: fix

#306 [EXTERNAL] Update definitions.ts to reflect true native expectation of the removeCustomerInfoUpdateListener (#280) by @jarvisluong
  README.md
  src/definitions.ts
  src/web.ts
Labels: fix

#292 Rename podspec to lowercase `RevenuecatPurchasesCapacitor.podspec`
  RevenuecatPurchasesCapacitor.podspec
  fastlane/Fastfile
Labels: fix

#313 Fix bump lane
  fastlane/Fastfile
Labels: ci
