Repository RevenueCat/purchases-capacitor, pull requests merged in 2025-01, with the labels that each got.

#381 Run PurchaseTester app with purchasesAreCompletedBy=REVENEUCAT by default
  example/purchase-tester/src/components/FunctionTesterContainer.tsx
Labels: pr:other

#366 Support Fetching and Redeeming Win-Back Offers on Custom Paywall
  README.md
  android/src/main/java/com/revenuecat/purchases/capacitor/PurchasesPlugin.kt
  example/purchase-tester/ios/App/App.xcodeproj/project.pbxproj
  example/purchase-tester/ios/App/App.xcodeproj/xcshareddata/xcschemes/App.xcscheme
  example/purchase-tester/ios/App/App/SKConfigFile.storekit
  example/purchase-tester/src/components/FunctionTesterContainer.tsx
  ios/Plugin/PluginHelperExtensions.swift
  ios/Plugin/PurchasesPlugin.m
  ios/Plugin/PurchasesPlugin.swift
  src/definitions.ts
  src/web.ts
Labels: pr:feat

#387 Capacitor V7 Support
  .circleci/config.yml
  .prettierignore
  RevenuecatPurchasesCapacitor.podspec
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
  example/purchase-tester/android/app/capacitor.build.gradle
  example/purchase-tester/android/app/src/main/AndroidManifest.xml
  example/purchase-tester/android/build.gradle
  example/purchase-tester/android/gradle/wrapper/gradle-wrapper.jar
  example/purchase-tester/android/gradle/wrapper/gradle-wrapper.properties
  example/purchase-tester/android/gradlew
  example/purchase-tester/android/gradlew.bat
  example/purchase-tester/android/variables.gradle
  example/purchase-tester/index.html
  example/purchase-tester/ios/App/App.xcodeproj/project.pbxproj
  example/purchase-tester/ios/App/Podfile
  example/purchase-tester/package.json
  ios/Plugin.xcodeproj/project.pbxproj
  ios/Podfile
  package.json
  rollup.config.js
  src/definitions.ts
  src/index.ts
  src/web.ts
Labels: pr:breaking, pr:other

#388 Release/10.0.0
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  VERSIONS.md
  android/src/main/java/com/revenuecat/purchases/capacitor/PurchasesPlugin.kt
  ios/Plugin/PurchasesPlugin.swift
  package.json
Labels: pr:next_release
